# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sql
  namespace: api
spec:
  provider: azure
  parameters:
    tenantId: "89b0ca46-8395-4efa-95fd-0e46f58cccb1"
 #  usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "d9236345-e74d-43f9-91ae-fbae9a3855f6"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "akvT082023"
    objects: |
      array:
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret